### ISSUE TITLE
what's wrong

### ISSUE THREAD

**Issue by redmoon02** [redmoon02/GRE_math#2]
## 이슈내용
pinky branch의 내용 master의 내용과 pull & push하기
## 상세내용
pinky와 master 병합하기는 이해. 하지만 branch 간에 pull & push 방법은 모르겠음.
## 체크리스트
- [x] branch 간에 pull & push 방법 찾아보기

**Comment by voidmain443** [comment]
확인 slack과의 연동 확인 완료

**Comment by voidmain443** [comment]
You are worng!
