### ISSUE TITLE
Summer camp - milestone request 

### ISSUE THREAD

**Issue by voidmain443** [redmoon02/GRE_math#4]
해야하는 것들을 정리해서 이번 서머 캠프에서 일정을 이수하시면 좋을 것 같습니다. 

이방학동안에는 깃을 통한 협업과 , LaTeX을 이용한 경제학보고서, 제텔카스텐 방법을이용한 지식 그래프 , Dendron을 통해 정리하는 법. 
통계교육원 강의와 ,한국은행 금요강좌를 이수할 계획입니다. 

이번 서머 마일스톤의 첫 시작은 math for English 입니다. 
지금 있는 repo는 이 math for English 세션을 위해 제작되었고, 강의를 할 수 있을 정도의 ipython과 markdown을 통해서 설명할 수 있으면 됩니다. 

이 리포는 총 4개의 과제로 구성되어있습니다. 

1. arithmetic
2.  algebra
3. geometry
4. data analysis

이 부분들을 폴더로 만들고 각 단원을 채우되 이중 각 단어의 숫자 및 수식을 읽는 부분은 오프라인으로 설명해야합니다. 
따라 IITJEE를 참고하셔도, GRE book을 참고하던 상관하진 않겠지만.  각 챕터별로 익숙해 지도록 합시다. 

8월 말에는 끝나야합니다.

**Comment by redmoon02** [comment]
숙지했습니다
